### ISSUE TITLE
Button positioning conflict with Crawl

### ISSUE THREAD

**Issue by JLUsr** [Jeryn99/Gliders#16]
The photo should explain what's going on here. It should also be noted that the text for the Glider Perspective toggle is missing the text-shadow effect.

![image](https://user-images.githubusercontent.com/47650360/221779483-b4a2575a-4af2-421b-8d13-de8977698948.png)

**Comment by Suff99** [comment]
Is this a compatibility issue with another mod?

**Comment by AliceCarlin** [comment]
Maybe move the glider perspective option over to a config file?

**Comment by CorneliusCornbread** [comment]
In the interim would it be possible to simply add a config option such that we can disable this button entirely in our modpacks? Then simply override the option using the same config file. I'd like to include this mod in our pack but it's causing problems in the UI.

**Comment by Jeryn99** [comment]
I will be moving this to https://github.com/Jeryn99/Gliders/issues/52
