### ISSUE TITLE
[Fabric 1.19.2] Issues with Crawl mod

### ISSUE THREAD

**Issue by kingkuys2123** [Jeryn99/Gliders#42]
Gliders 1.1.3
Crawl 0.11.1

Fabric 0.14.22
Fabric API 0.76.0

## Crawling While Gliding
When pressing the [Crawl](https://www.curseforge.com/minecraft/mc-mods/crawl) button while gliding, this will happen

![image](https://github.com/VentureCraftMods/MC-Gliders/assets/114457180/6fdd4892-92c6-4796-b481-559049eb63f5)

## Button Position

![image](https://github.com/VentureCraftMods/MC-Gliders/assets/114457180/0bf8c689-7193-4dad-8d42-d990d1ae1002)

**Comment by Jeryn99** [comment]
Moving to https://github.com/Jeryn99/Gliders/issues/52
