### ISSUE TITLE
[Suggestion]: Compatibility with EpicFight animations

### ISSUE THREAD

**Issue by Hakuyako** [Jeryn99/Gliders#58]
Can you please adding compatibility with EpicFight's animations?

This can be easy done by temporarily disable EpicFight's animations while gliding.

**Comment by Jeryn99** [comment]
Sure, if it's easy, point me in the direction of their codebase that does it

**Comment by Hakuyako** [comment]
> Sure, if it's easy, point me in the direction of their codebase that does it

Their repository: https://github.com/Yesssssman/epicfightmod
and their wiki: https://epicfight-docs.readthedocs.io/API/Starting/

**Comment by Jeryn99** [comment]
That's not what I asked for, I asked you to show me where in code, you are indicating that it is easy, so you must have a understanding of where its done

**Comment by Hakuyako** [comment]
> That's not what I asked for, I asked you to show me where in code, you are indicating that it is easy, so you must have a understanding of where its done

Sorry, actually I don't understand coding and maybe wrong to claiming this was "easy". 

But there is a mod that does similar something, canceling the EpicFight's movements while the paraglider is gliding, here is their code. (Not sure if I'm doing this thing right)
https://github.com/CravenCraft/EpicParagliders/blob/release/1.18.2/src/main/java/net/cravencraft/epicparagliders/events/FixParagliderRender.java
