### ISSUE TITLE
Incompatibility with Sword Blocking Mechanics mod.

### ISSUE THREAD

**Issue by Husenberg** [Jeryn99/Gliders#64]
I love the mod, but for some reason it disables blocking in the aforementioned mod. The sword just jitters instead of blocking. Tested it on a new instance with just SBM and Gliders (with dependencies) installed and it still does the jitter. Weird, because right click isn't used in the mod.

https://github.com/Jeryn99/MC-Gliders/assets/17479083/3d6ba488-5cd6-4a1f-a590-c1b0b42f5121

**Comment by Jeryn99** [comment]
Is this Forge or Fabric?

**Comment by Husenberg** [comment]
1.20.1 Fabric

**Comment by Jeryn99** [comment]
Thanks, will take a look when I can
