### ISSUE TITLE
[BUG] Glider Perspective toggle overlaps with operator tabs button (Fabric 1.20.1)

### ISSUE THREAD

**Issue by benadrylcabbagepatch** [Jeryn99/Gliders#70]
![bug](https://github.com/user-attachments/assets/13b3d50f-ec11-46f6-9f6c-f082d7af6cee)

**Comment by JaydenLyte** [comment]
This happens in the latest forge version as well.
![image](https://github.com/user-attachments/assets/b4ccca6e-6811-43e5-a6b7-abe43989a073)

The Operator Tab button was added to Minecraft in version 1.19.3.
![image](https://github.com/user-attachments/assets/974ea8b1-98c1-4a50-91be-5d078e1295e9)

**Comment by Jeryn99** [comment]
Track here please https://github.com/Jeryn99/Gliders/issues/52
