### ISSUE TITLE
1.21?

### ISSUE THREAD

**Issue by xubilinhaloko** [Jeryn99/Gliders#72]
Hey, any plans on porting this mod to 1.21?

**Comment by Jeryn99** [comment]
Yes

**Comment by adaliszk** [comment]
I see, I will keep trying just in case I could open a PR

**Comment by adaliszk** [comment]
@Jeryn99 would it make sense to open a new one to track the progress? Other than that I can offer a bounty on it, but not sure that helps.

**Comment by Jeryn99** [comment]
> [@Jeryn99](https://github.com/Jeryn99) would it make sense to open a new one to track the progress? Other than that I can offer a bounty on it, but not sure that helps.

It's mostly motivation based, as I have a considerable amount of things to alter before I resume 1.21.1 - I can open another issue if you really want me to?

**Comment by adaliszk** [comment]
Yeah, I was trying to upgrade but ran into some libraries that need to be also updated and kinda considering if worth the effort to perhaps drop the libraries and keep it simple or go and contirbute to the libraries that I probably won't ever use 😄

**Comment by Jeryn99** [comment]
Some of these libraries are leaving us: https://github.com/Jeryn99/Gliders/tree/1.20.1-standalone

**Comment by adaliszk** [comment]
Ah nice, that might actually make it possible to upgrade 🤔
