### ISSUE TITLE
what is the config file called?

### ISSUE THREAD

**Issue by R0gyman** [Jeryn99/Gliders#73]
I'm sick of my gliders burning in the nether and being struck by lightning 
if there ist a config file to get rid of these there should be 👍

**Comment by Jeryn99** [comment]
Please read the mod description...

You need to upgrade your glider....

**Comment by R0gyman** [comment]
> Please read the mod description...
> 
> You need to upgrade your glider....

why does my netherite glider burn in the nether
pls add a config to disable this entirely including the rain

**Comment by Jeryn99** [comment]
Upgrade your glider item.
