### ISSUE TITLE
(Re)add the custom recipe type in the 1.20 branch

### ISSUE THREAD

**Issue by WouterB15** [Jeryn99/Gliders#74]
Hey, any ETA on when the custom recipe type is being (re)added to 1.20.x? Because at the moment it's spitting a lot of errors, and I noticed in the code you've got it just commented out.
https://github.com/Jeryn99/Gliders/blob/1.20/common/src/main/java/net/venturecraft/gliders/common/recipe/GliderUpgradingRecipe.java
![image](https://github.com/user-attachments/assets/e1cfa944-7c34-4510-9ded-25845a8f5345)
And then there's about 20 of these.

**Comment by Jeryn99** [comment]
The recipe json files don’t actively do anything anymore as the upgrading was moved to anvils, it seems I didn’t catch these files 

I’ll get it sorted soon

**Comment by WouterB15** [comment]
I had no usages show up for the upgrades, even with using anvils (used EMI to check this). Don't know if that is part of the same issue?
Anyway, look forward to seeing the fix, thanks for your time and effort!

**Comment by Jeryn99** [comment]
![image](https://github.com/user-attachments/assets/a936553c-fa1c-4762-858f-fa95d8097586)


Update 1.1.6 will be up on all platforms tonight, please download when available

(Not really sure why EMI doesn't see the Anvil recipes
